# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

resources:
  repositories:
    - repository: templates
      type: github
      name: kablanx/templates
      endpoint: github.com_kablanx
      
extends:
  template: start.yml@templates
  parameters:
    buildSteps:
      - bash: echo Test #Passes
        displayName: succeed

pool:
  vmImage: ubuntu-latest

